=== JohnDeAn16/LIA/schema/DocSchema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" 
targetNamespace="http://www.example.org/metaSchema" 
xmlns:tns="http://www.example.org/metaSchema" 
elementFormDefault="qualified" 
xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="ForberedelseUnderlag">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="AnkomstDatum" type="date"/>
				<xs:element name="TidsStampel" type="time"/>
				<xs:element name="TotalLaddning" type="boolean"/>
				<xs:element name="Filer">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="Fil" minOccurs="1" maxOccurs="unbounded">
								<xs:complexType>
									<xs:simpleContent>
										<xs:extension base="string">
											<attribute name="amne" type="string" use="required"/>
										</xs:extension>
									</xs:simpleContent>
								</xs:complexType>
							</xs:element>
							</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</schema>

=== JohnDeAn16/LIA/XMLUnderlag/Doc.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:ForberedelseUnderlag xmlns:tns="http://www.example.org/metaSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.example.org/metaSchema ../schema/DocSchema.xsd ">
  <tns:AnkomstDatum>2001-01-01</tns:AnkomstDatum>
  <tns:TidsStampel>12:00:00</tns:TidsStampel>
  <tns:TotalLaddning>true</tns:TotalLaddning>
  <tns:Filer>
    <tns:Fil amne="GrundOchMarginal">GrundMarginal.xml</tns:Fil>
    <tns:Fil amne="GrundOchMarginal">GrundMarginalInvalid.xml</tns:Fil>
    <tns:Fil amne="AldersInverkan">AldersInverkan.xml</tns:Fil>
    <tns:Fil amne="GrundOchMarginal">GrundMarginalMultuValues.xml</tns:Fil>
  </tns:Filer>
</tns:ForberedelseUnderlag>
